name: dask-mini-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - dask
  - distributed
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets
  - graphviz
  - python-graphviz
  - scikit-learn
  - dask-ml
  - coiled=0.0.61
  - s3fs