name: create-coiled-datasets-m1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.11
  - numpy=1.21.1
  - coiled>0.0.42
  - dask=2021.07.1
  - distributed=2021.07.1
  - ipython
  - jupyterlab
  - nodejs
  - dask-labextension
  - ipykernel
  - seaborn
  - fastparquet
  - pyarrow
  - ipywidgets
  - python-graphviz
  - imageio
  - scipy
  - blosc
  - lz4=3.1.3
  - pandas=1.3.1