name: datasets-m1-test-florian
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.11
  - pandas==1.3.0
  - dask==2021.07.1
  - dask-core==2021.07.2
  - distributed==2021.07.2
  - pyarrow==4.0.1
  - jupyterlab
  - dask-labextension==5.1.0
  - ipykernel
  - s3fs
  - coiled
  - lz4
