name: dask-delayed
channel:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - distributed
  - pandas
  - numpy
  - scikit-learn
  - python-graphviz
  - jupyterlab
  - pip
  - pip:
    - dask-labextension>=3.0.0
