name: xgboost-mortgage
channels:
  - conda-forge
dependencies:
  - coiled
  - dask-ml
  - dask>=2.23.0
  - dask-labextension
  - dask-xgboost
  - distributed>=2.23.0
  - fastparquet
  - ipywidgets
  - jupyterlab
  - pandas>=1.1.0
  - pip
  - s3fs
  - xgboost>=1.3.0
